### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by noman-evva** [nginx-clojure/nginx-access-plus#2]
I followed the installation instructions and try to use this module in Nginx version 1.10.3. In my site-enable/default i have added these settings:
**allow_method 192.168.4.14 get|head|post|delete|put;
deny_method all all;**

After restarting a Nginx service gives an error:
unknown directive "allow_method" in /etc/nginx/sites-enable 

Any idea why it is not working?

**Comment by xfeep** [comment]
Please make sure that the nginx service is using the compiled result.
By default the installation path is /usr/local/nginx  which can be overwritten by  `--prefix=path`  when you build it from source.
